### ISSUE TITLE
Feature Request: option to hide some buttons

### ISSUE THREAD

**Issue by ewonais** [cpiber/NebulaEnhance#50] opened 2023-07-04 16:23 UTC
Some buttons i newer use or use the shortcut insted.
Feles clutterd with so many buttons.
Also an option to mowe volume to the right.
Maybe also make the order changeble.
![image](https://github.com/cpiber/NebulaEnhance/assets/86527854/dc8bce51-9f15-489c-a19e-4f29f363cf99)
![image](https://github.com/cpiber/NebulaEnhance/assets/86527854/36181ac2-e0d5-42ce-9361-26363b855515)
This button is useless in fullscren so shuld be hidden then.

**Comment by cpiber** [comment] 2023-07-21 12:39
I agree, it can be a bit cluttered, I'll think about some ways to make this better

>  This button is useless in fullscren so shuld be hidden then.

I disagree. This button does not have anything to do with fullscreen, it changes the amount of space the player takes up, regardless of windowed or fullscreen.

---

I've noticed that you've opened a few issues now, and I thank you for contributing.
But often your English is somewhat broken, some could be typos, but others seem intentionally incorrect. Could you please take more care to write proper English? Especially as a non-native speaker, it can sometimes be hard to see what you mean. (And if you're concerned about AI, I doubt this helps)

**Comment by cpiber** [comment] 2023-07-29 19:43
Played around with it, and I think I'm happy with the current result, please try it out:
[enhancer_for_nebula-1.3.5.1.zip](https://github.com/cpiber/NebulaEnhance/files/12207863/enhancer_for_nebula-1.3.5.1.zip)
I plan on releasing the next version fairly soon, since the controls and queue buttons were broken, so please send your feedback soon @ewonais 

To install:
- in Chrome, please go to Setting, click Extensions (lower left), enable Developer Mode (upper right) and select "Load unpacked". Here select the unzipped folder (should contain folders _locale, icons, scripts, styles).
- in Firefox, please go to about:addons, click on the gear (top right), select Debug addons and click "Load Temporary Addon". Here select the zip you downloaded.

**Comment by ewonais** [comment] 2023-07-30 07:28
![image](https://github.com/cpiber/NebulaEnhance/assets/86527854/1b93de83-a420-424a-a86a-7b628c956cef)
![image](https://github.com/cpiber/NebulaEnhance/assets/86527854/045818f3-1093-4480-baff-7304ce130f19)
![image](https://github.com/cpiber/NebulaEnhance/assets/86527854/43334fd5-7d70-465a-a77e-5f7f356d56e0)
hidden buttons still show
left and right semes to work

moving audio to the right side make so it somtimes werd when opening, depends on where the mouse is
![image](https://github.com/cpiber/NebulaEnhance/assets/86527854/ab6fcc11-0d5f-4424-aa4a-4dbb349881e1)


is ther a hotkey for this?
![image](https://github.com/cpiber/NebulaEnhance/assets/86527854/53cf9934-b2eb-4c75-a4c8-22ded2eb4820)

**Comment by cpiber** [comment] 2023-07-30 08:00
>  hidden buttons still show
> moving audio to the right side make so it somtimes werd when opening, depends on where the mouse is

I'll check that, I haven't noticed anything on my side

> is ther a hotkey for this?

You mean for opening the configuration? No, but the player should automatically update, so you can just open it in a separate tab to see how it looks like

**Comment by cpiber** [comment] 2023-07-30 08:10
Should have waited before sending my reply, I can't reproduce any of that, neither with a new build, nor with the one I sent you. I am using Firefox 116 to test this.

That the hidden buttons still show should be a CSS problem, could you please show the inspector for one of them? Right click > Inspect Element, make sure the top element (e.g. the one with id "toggle-play-button") is selected, and screenshot the HTML side and the CSS please.

>  moving audio to the right side make so it somtimes werd when opening, depends on where the mouse is

Also can't reproduce this. To me, it looks like the icon didn't properly reset from expanding (when you hover it shows a slider), but that is Nebula functionality, so I don't think I can or will fix this.

> > is ther a hotkey for this?
> 
> You mean for opening the configuration? No, but the player should automatically update, so you can just open it in a separate tab to see how it looks like

My bad, the image didn't load. There isn't one, but I can configure it.

**Comment by ewonais** [comment] 2023-07-30 09:22
using cromium (vivaldi), same with edge so might be a peoblem for all cromium based browsers
tried to disable all other extansions but dident fix it, same in private window
inspekt:
![image](https://github.com/cpiber/NebulaEnhance/assets/86527854/c217fdae-8dd4-4ef5-ab2e-40aeb170df49)

**Comment by cpiber** [comment] 2023-07-30 09:42
> That the hidden buttons still show should be a CSS problem

That was it. Chromium applies different rules to extension stylesheets, that bit me before, should be fixed now.

> moving audio to the right side make so it somtimes werd when opening, depends on where the mouse is

seems to be a problem with the volume indicator from my side, "always show" needs to be disabled for that to happen.

Thank you for your help, please try this version, it should work in Chromium as well:
[enhancer_for_nebula-1.3.5.2.zip](https://github.com/cpiber/NebulaEnhance/files/12208859/enhancer_for_nebula-1.3.5.2.zip)

**Comment by ewonais** [comment] 2023-07-30 09:58
works! and good to hawe a shotcut.

**Comment by VK2XPT** [comment] 2023-07-30 09:59
Works for me :)

**Closed** 2023-07-30 10:11 UTC
Labels: enhancement, implemented
